# The iris data set

This is a classic 'toy' data set used for machine learning testing is the iris data set. 

The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimetres.

It comes preloaded in scikit learn. Let's load it and have a look at it. 

In [34]:
import numpy as np
from sklearn import datasets


iris=datasets.load_iris()

In [35]:
# The iris dataset is an object that contains a number of elements:

print (list(iris))

['data', 'target', 'target_names', 'DESCR', 'feature_names']


In [36]:
# feature_names shows data field titles:

print (iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [37]:
# data is the data for each sample; columns described by feature_names:
# lets' print just the first 10 roes
print (iris.data[0:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [38]:
# target_names lists types of iris identified:

print (iris.target_names)

['setosa' 'versicolor' 'virginica']


In [39]:
# target lists the type of iris in each row of data:
# this maps to the target_names

print (iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [40]:
# DESCR gives us description of the data set:

print (iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

## Data sets in scikit learn

load_boston: boston house-prices dataset (regression).

load_iris: iris dataset (classification).

load_diabetes: diabetes dataset (regression).

load_digits: digits dataset (classification).

load_linnerud: linnerud dataset (multivariate regression).

load_wine: wine dataset (classification).

load_breast_cancer: breast cancer wisconsin dataset (classification).

## Other sources of test data sets

https://archive.ics.uci.edu/ml/datasets.html

https://blog.bigml.com/list-of-public-data-sources-fit-for-machine-learning/